CREATE TABLE FACULTY
(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
FACULTY TEXT(10) NOT NULL,
FACULTY_NAME TEXT(50)
);

CREATE TABLE PULPIT
(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
PULPIT TEXT(10) NOT NULL,
PULPIT_NAME TEXT(100),
FACULTY_ID INTEGER NOT NULL,
FOREIGN KEY(FACULTY_ID) REFERENCES FACULTY(ID)
);

CREATE TABLE TEACHER
(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
TEACHER TEXT(10) NOT NULL,
TEACHER_NAME TEXT(50),
PULPIT_ID INTEGER NOT NULL,
FOREIGN KEY(PULPIT_ID) REFERENCES PULPIT(ID)
);

CREATE TABLE SUBJECT
(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
SUBJECT TEXT(10) NOT NULL,
SUBJECT_NAME TEXT(50) NOT NULL,
PULPIT_ID INTEGER NOT NULL,
FOREIGN KEY(PULPIT_ID) REFERENCES PULPIT(ID)
);

CREATE TABLE AUDITORIUM_TYPE
(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
AUDITORIUM_TYPE TEXT(10) NOT NULL,
AUDITORIUM_TYPENAME TEXT(30) NOT NULL
);

CREATE TABLE AUDITORIUM
(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
AUDITORIUM TEXT(10) NOT NULL,
AUDITORIUM_NAME TEXT(200),
AUDITORIUM_CAPACITY INTEGER,
AUDITORIUM_TYPE_ID INTEGER NOT NULL,
FOREIGN KEY(AUDITORIUM_TYPE_ID) REFERENCES AUDITORIUM_TYPE(ID)
);


-- Вставка данных в таблицу FACULTY
INSERT INTO FACULTY (FACULTY, FACULTY_NAME) VALUES ('FAC1', 'Факультет 1');
INSERT INTO FACULTY (FACULTY, FACULTY_NAME) VALUES ('FAC2', 'Факультет 2');

-- Вставка данных в таблицу PULPIT
INSERT INTO PULPIT (PULPIT, PULPIT_NAME, FACULTY_ID) VALUES ('PUL1', 'Кафедра 1', 3);
INSERT INTO PULPIT (PULPIT, PULPIT_NAME, FACULTY_ID) VALUES ('PUL2', 'Кафедра 2', 4);

-- Вставка данных в таблицу TEACHER
INSERT INTO TEACHER (TEACHER, TEACHER_NAME, PULPIT_ID) VALUES ('TEA1', 'Преподаватель 1', 3);
INSERT INTO TEACHER (TEACHER, TEACHER_NAME, PULPIT_ID) VALUES ('TEA2', 'Преподаватель 2', 4);

-- Вставка данных в таблицу SUBJECT
INSERT INTO SUBJECT (SUBJECT, SUBJECT_NAME, PULPIT_ID) VALUES ('SUB1', 'Предмет 1', 3);
INSERT INTO SUBJECT (SUBJECT, SUBJECT_NAME, PULPIT_ID) VALUES ('SUB2', 'Предмет 2', 4);

-- Вставка данных в таблицу AUDITORIUM_TYPE
INSERT INTO AUDITORIUM_TYPE (AUDITORIUM_TYPE, AUDITORIUM_TYPENAME) VALUES ('TYPE1', 'Тип аудитории 1');
INSERT INTO AUDITORIUM_TYPE (AUDITORIUM_TYPE, AUDITORIUM_TYPENAME) VALUES ('TYPE2', 'Тип аудитории 2');

-- Вставка данных в таблицу AUDITORIUM
INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY, AUDITORIUM_TYPE_ID) VALUES ('AUD1', 'Аудитория 1', 30, 3);
INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY, AUDITORIUM_TYPE_ID) VALUES ('AUD2', 'Аудитория 2', 40, 4);

commit;

INSERT INTO AUDITORIUM_TYPE (AUDITORIUM_TYPE, AUDITORIUM_TYPENAME) VALUES ('ЛБ-К', 'Компьютерная');

INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY, AUDITORIUM_TYPE_ID) VALUES ('110-1', '110-1', 20, 5);
INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY, AUDITORIUM_TYPE_ID) VALUES ('308-4', '308-4', 20, 5);

commit;


INSERT INTO PULPIT (PULPIT, PULPIT_NAME, FACULTY_ID) VALUES ('СК', 'Секретная Кафедра', 3);
INSERT INTO PULPIT (PULPIT, PULPIT_NAME, FACULTY_ID) VALUES ('НСК', 'Не Секретная Кафедра', 4);

INSERT INTO PULPIT (PULPIT, PULPIT_NAME, FACULTY_ID) VALUES ('БК', 'Бесполезная Кафедра', 3);
INSERT INTO PULPIT (PULPIT, PULPIT_NAME, FACULTY_ID) VALUES ('ПК', 'Полезная кафедра', 4);

INSERT INTO PULPIT (PULPIT, PULPIT_NAME, FACULTY_ID) VALUES ('КА', 'Кафедра Авиамоделирования', 3);
INSERT INTO PULPIT (PULPIT, PULPIT_NAME, FACULTY_ID) VALUES ('КИИ', 'Кафедра Искусственного Интелекта', 4);